spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka